package editor.xmleditor;


import adapters.FileSystemObject;

import javax.swing.*;
import javax.xml.bind.JAXBException;
import javax.xml.parsers.SAXParser;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;

public class XMLEditorFrame extends javax.swing.JFrame {

    /**
     * Creates new form XMLEditorFrame
     */
    private File file;
    public XMLEditorFrame(File file) {
        this.file=file;
        this.setTitle("XML Editor Yermilov");
        initComponents();
        initButtonsListeners();
        infoTextArea.setLineWrap(true);
        infoTextArea.setWrapStyleWord(true);
        infoTextArea.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        parsersButtonGroup = new javax.swing.ButtonGroup();
        dataLabel = new javax.swing.JLabel();
        controlPanel = new javax.swing.JPanel();
        textPaneControllerPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        nameCheckBox = new javax.swing.JCheckBox();
        descriptionCheckBox = new javax.swing.JCheckBox();
        versionCheckBox = new javax.swing.JCheckBox();
        typeCheckBox = new javax.swing.JCheckBox();
        authorCheckBox = new javax.swing.JCheckBox();
        licenseCheckBox = new javax.swing.JCheckBox();
        nameTextField = new javax.swing.JTextField();
        descriptionTextField = new javax.swing.JTextField();
        versionTextField = new javax.swing.JTextField();
        typeTextField = new javax.swing.JTextField();
        authorTextField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        parserChoosingPanel = new javax.swing.JPanel();
        domRadioButton = new javax.swing.JRadioButton();
        SAXRadioButton = new javax.swing.JRadioButton();
        marshallingRadioButton = new javax.swing.JRadioButton();
        textPanePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoTextArea = new javax.swing.JTextArea();
        xslButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dataLabel.setText("Data:");
        dataLabel.setName("dataLabel"); // NOI18N

        controlPanel.setName("tagsSelectorsPanel"); // NOI18N

        textPaneControllerPanel.setName("textPaneControllerPanel"); // NOI18N

        jButton1.setText("Search");

        jButton2.setText("Clear");

        javax.swing.GroupLayout textPaneControllerPanelLayout = new javax.swing.GroupLayout(textPaneControllerPanel);
        textPaneControllerPanel.setLayout(textPaneControllerPanelLayout);
        textPaneControllerPanelLayout.setHorizontalGroup(
                textPaneControllerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(textPaneControllerPanelLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        textPaneControllerPanelLayout.setVerticalGroup(
                textPaneControllerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, textPaneControllerPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(textPaneControllerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1)
                                        .addComponent(jButton2))
                                .addContainerGap())
        );

        nameCheckBox.setText("Name");
        nameCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameCheckBoxActionPerformed(evt);
            }
        });

        descriptionCheckBox.setText("Description");

        versionCheckBox.setText("Version");

        typeCheckBox.setText("Type");

        authorCheckBox.setText("Author");

        licenseCheckBox.setText("License");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Educational", "Free", "Paid" }));

        parserChoosingPanel.setName("parserChoosingPanel"); // NOI18N

        parsersButtonGroup.add(domRadioButton);
        domRadioButton.setText("DOM");

        parsersButtonGroup.add(SAXRadioButton);
        SAXRadioButton.setText("SAX");

        parsersButtonGroup.add(marshallingRadioButton);
        marshallingRadioButton.setText("Marshalling");

        javax.swing.GroupLayout parserChoosingPanelLayout = new javax.swing.GroupLayout(parserChoosingPanel);
        parserChoosingPanel.setLayout(parserChoosingPanelLayout);
        parserChoosingPanelLayout.setHorizontalGroup(
                parserChoosingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(parserChoosingPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(parserChoosingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(domRadioButton)
                                        .addComponent(SAXRadioButton)
                                        .addComponent(marshallingRadioButton))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        parserChoosingPanelLayout.setVerticalGroup(
                parserChoosingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(parserChoosingPanelLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(domRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SAXRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(marshallingRadioButton)
                                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
                controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(controlPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(controlPanelLayout.createSequentialGroup()
                                                .addComponent(nameCheckBox)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(controlPanelLayout.createSequentialGroup()
                                                .addComponent(descriptionCheckBox)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                                .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(controlPanelLayout.createSequentialGroup()
                                                .addComponent(versionCheckBox)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(versionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(controlPanelLayout.createSequentialGroup()
                                                .addComponent(typeCheckBox)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(typeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                                                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(authorCheckBox)
                                                        .addComponent(licenseCheckBox))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(authorTextField)
                                                        .addComponent(jComboBox1, 0, 243, Short.MAX_VALUE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                                                .addComponent(parserChoosingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textPaneControllerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
                controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(controlPanelLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nameCheckBox)
                                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(descriptionCheckBox)
                                        .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(versionCheckBox)
                                        .addComponent(versionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(typeCheckBox)
                                        .addComponent(typeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(authorCheckBox)
                                        .addComponent(authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(licenseCheckBox)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(parserChoosingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textPaneControllerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        textPanePanel.setName("textPanePanel"); // NOI18N

        infoTextArea.setColumns(20);
        infoTextArea.setRows(5);
        jScrollPane1.setViewportView(infoTextArea);

        javax.swing.GroupLayout textPanePanelLayout = new javax.swing.GroupLayout(textPanePanel);
        textPanePanel.setLayout(textPanePanelLayout);
        textPanePanelLayout.setHorizontalGroup(
                textPanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );
        textPanePanelLayout.setVerticalGroup(
                textPanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
        );

        xslButton.setText("To XSL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(dataLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(xslButton)
                                                .addGap(30, 30, 30)))
                                .addComponent(textPanePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(25, 25, 25)
                                                .addComponent(textPanePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(25, 25, 25)
                                                                .addComponent(dataLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(xslButton)
                                                                .addGap(11, 11, 11)))
                                                .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void nameCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private Software constructFilterSoftware(){
        return getFilter();
    }
    private String newLine="\n";
    private void initButtonsListeners(){
        jButton1.setActionCommand("Search");
        jButton1.addActionListener(e -> {
            if(domRadioButton.isSelected()){
                infoTextArea.append(DOMParser.getDOMXML(file,constructFilterSoftware())+newLine);
            }
            else{
                if(marshallingRadioButton.isSelected()){
                    try {
                        infoTextArea.append(Unmarshalling.unmarshall(file,constructFilterSoftware()).toString()+newLine);
                    } catch (JAXBException e1) {
                        e1.printStackTrace();
                    } catch (IOException e1) {
                        e1.printStackTrace();
                    }
                }
                else{
                    if(SAXRadioButton.isSelected()){

                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Please select parser");
                    }
                }
            }
        });
        jButton2.addActionListener(e -> infoTextArea.setText(""));
        xslButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                XSLConverter.convert(file);
            }
        });
    }

    public Software getFilter(){
        Software filter = new Software();
        if(nameCheckBox.isSelected()){
            filter.setName(nameTextField.getText());
        }
        if(typeCheckBox.isSelected()){
            filter.setType(typeTextField.getText());
        }
        if(versionCheckBox.isSelected()){
            filter.setVersion(versionTextField.getText());
        }
        if(descriptionCheckBox.isSelected()){
            filter.setDescription(descriptionTextField.getText());
        }
        if(authorCheckBox.isSelected()){
            filter.setAuthor(authorTextField.getText());
        }
        if(licenseCheckBox.isSelected()){
            filter.setLicense(jComboBox1.getSelectedItem().toString());
        }
        return filter;
    }
    // Variables declaration - do not modify                     
    private javax.swing.JRadioButton SAXRadioButton;
    private javax.swing.JCheckBox authorCheckBox;
    private javax.swing.JTextField authorTextField;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JCheckBox descriptionCheckBox;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JRadioButton domRadioButton;
    private javax.swing.JTextArea infoTextArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox licenseCheckBox;
    private javax.swing.JRadioButton marshallingRadioButton;
    private javax.swing.JCheckBox nameCheckBox;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPanel parserChoosingPanel;
    private javax.swing.ButtonGroup parsersButtonGroup;
    private javax.swing.JPanel textPaneControllerPanel;
    private javax.swing.JPanel textPanePanel;
    private javax.swing.JCheckBox typeCheckBox;
    private javax.swing.JTextField typeTextField;
    private javax.swing.JCheckBox versionCheckBox;
    private javax.swing.JTextField versionTextField;
    private javax.swing.JButton xslButton;
    // End of variables declaration                   
}
